### ISSUE TITLE
Images not showing with raw image coming from Plugin

### ISSUE THREAD

**Issue by totoantibes** [Touch-N-Stars/Touch-N-Stars#169]
For imaging I am running a plugin that get RAW images from DSLR. https://github.com/totoantibes/NinaLumixPlugin
In that config i am not seeing the images in the running sequence page.

**Comment by JohannesWorks** [comment]
That sounds like the same problem as https://github.com/Touch-N-Stars/Touch-N-Stars/issues/149
There will soon be a new release in which the error is fixed.
Please let me know after the update if it works or not

**Comment by JohannesWorks** [comment]
The update is available.
Does the error still occur with it

**Comment by totoantibes** [comment]
I am away right now. will try next week.
thanls  
    On Wednesday, February 5, 2025 at 03:33:28 PM GMT+1, JohannesWorks ***@***.***> wrote:  
 
 


The update is available.
Does the error still occur with it

**Comment by JohannesWorks** [comment]
is included in the next version
